// Owner: shelf-clipboard.
import Foundation
import Testing

@testable import SuperNotchCore

@Suite("ClipboardCaptureFilter")
struct ClipboardCaptureFilterTests {
    let text = "public.utf8-plain-text"

    @Test func skipsConcealedOwnAndIgnored() {
        #expect(
            ClipboardCaptureFilter.decide(
                types: [text, "org.nspasteboard.ConcealedType"], sourceBundleID: nil, ignoredBundleIDs: []) != .capture)
        #expect(
            ClipboardCaptureFilter.decide(
                types: [text, ClipboardCaptureFilter.ownMarkerType], sourceBundleID: nil, ignoredBundleIDs: [])
                != .capture)
        #expect(
            ClipboardCaptureFilter.decide(
                types: [text], sourceBundleID: "com.bitwarden.desktop",
                ignoredBundleIDs: AppSettings.defaultIgnoredApps) != .capture)
        #expect(
            ClipboardCaptureFilter.decide(
                types: [text], sourceBundleID: "com.apple.Safari",
                ignoredBundleIDs: AppSettings.defaultIgnoredApps) == .capture)
    }

    @Test(arguments: [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type", ClipboardCaptureFilter.ownMarkerType,
    ])
    func skipsEveryMarker(marker: String) {
        let decision = ClipboardCaptureFilter.decide(
            types: ["public.utf8-plain-text", marker], sourceBundleID: "com.apple.TextEdit", ignoredBundleIDs: [])
        #expect(decision == .skip(reason: marker))
    }

    @Test func emptyTypesAreSkipped() {
        #expect(
            ClipboardCaptureFilter.decide(types: [], sourceBundleID: nil, ignoredBundleIDs: [])
                == .skip(reason: "empty"))
    }

    @Test func ignoredAppsMatchCaseInsensitivelyAndTrimmed() {
        #expect(
            ClipboardCaptureFilter.decide(
                types: [text], sourceBundleID: "COM.1Password.1Password ", ignoredBundleIDs: ["com.1password.1password"])
                == .skip(reason: "ignored app"))
        #expect(
            ClipboardCaptureFilter.decide(types: [text], sourceBundleID: "   ", ignoredBundleIDs: ["   "]) == .capture)
    }

    @Test func sourceMarkerWinsOverFrontmost() {
        #expect(
            ClipboardCaptureFilter.sourceBundleID(marker: "com.bitwarden.desktop", frontmost: "com.apple.Safari")
                == "com.bitwarden.desktop")
        #expect(ClipboardCaptureFilter.sourceBundleID(marker: " ", frontmost: "com.apple.Safari") == "com.apple.Safari")
        #expect(ClipboardCaptureFilter.sourceBundleID(marker: nil, frontmost: nil) == nil)
    }

    @Test func dedupeAndLimit() {
        let t = Date(timeIntervalSince1970: 0)
        var entries: [ClipboardEntry] = []
        for index in 0..<5 {
            entries = ClipboardCaptureFilter.insert(
                ClipboardEntry(content: .text("\(index)"), capturedAt: t), into: entries, limit: 3)
        }
        #expect(entries.map(\.previewText) == ["4", "3", "2"])
        entries = ClipboardCaptureFilter.insert(
            ClipboardEntry(content: .text("2"), capturedAt: t), into: entries, limit: 3)
        #expect(entries.map(\.previewText) == ["2", "4", "3"])
        #expect(ClipboardEntry.hash(of: .text("a")) == ClipboardEntry.hash(of: .text("a")))
        #expect(ClipboardEntry.hash(of: .text("a")) != ClipboardEntry.hash(of: .link("a")))
    }

    @Test func dedupeKeepsPinAndPinnedSurviveTheLimit() {
        let t = Date(timeIntervalSince1970: 0)
        var entries = [ClipboardEntry(content: .text("keep"), capturedAt: t, pinned: true)]
        for index in 0..<10 {
            entries = ClipboardCaptureFilter.insert(
                ClipboardEntry(content: .text("\(index)"), capturedAt: t), into: entries, limit: 2)
        }
        #expect(entries.map(\.previewText) == ["9", "8", "keep"])
        entries = ClipboardCaptureFilter.insert(
            ClipboardEntry(content: .text("keep"), capturedAt: t + 5), into: entries, limit: 2)
        #expect(entries.first?.previewText == "keep")
        #expect(entries.first?.pinned == true)
        #expect(entries.count == 3)
        #expect(entries.filter { $0.previewText == "keep" }.count == 1)
    }

    @Test func imageHashDedupe() {
        let t = Date(timeIntervalSince1970: 0)
        let data = Data([1, 2, 3, 4])
        let hash = ClipboardDigest.imageContentHash(of: data)
        #expect(hash == ClipboardDigest.imageContentHash(of: Data([1, 2, 3, 4])))
        #expect(hash != ClipboardDigest.imageContentHash(of: Data([1, 2, 3, 5])))
        var entries: [ClipboardEntry] = []
        entries = ClipboardCaptureFilter.insert(
            ClipboardEntry(content: .image(relativePath: "images/a.png", pixelWidth: 1, pixelHeight: 1),
                capturedAt: t, contentHash: hash), into: entries, limit: 10)
        entries = ClipboardCaptureFilter.insert(
            ClipboardEntry(content: .image(relativePath: "images/a.png", pixelWidth: 1, pixelHeight: 1),
                capturedAt: t + 1, contentHash: hash), into: entries, limit: 10)
        #expect(entries.count == 1)
    }

    @Test func fnvMatchesKnownVector() {
        // FNV-1a 64 of "a" is 0xaf63dc4c8601ec8c.
        #expect(ClipboardDigest.fnv1a64(Data("a".utf8)) == 0xaf63_dc4c_8601_ec8c)
        #expect(ClipboardDigest.fnv1a64(Data()) == 0xcbf2_9ce4_8422_2325)
    }
}
