import Foundation

// Owner: shelf-clipboard. Signature FROZEN (SPEC §D.3).
// Pure decision whether a pasteboard change is recorded (see http://nspasteboard.org), plus the
// de-duplicating, size-capped insert used by the clipboard history.

public enum ClipboardCaptureFilter {
    /// Marker type SuperNotch adds to its own pasteboard writes so they are not re-captured.
    public static let ownMarkerType = "io.github.snakez3101.supernotch.own"

    /// Types that mean "do not record" (password managers, transient/auto-generated content).
    public static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        ownMarkerType,
    ]

    /// Type announcing the source app (optional convention).
    public static let sourceType = "org.nspasteboard.source"

    public enum Decision: Sendable, Hashable {
        case capture
        case skip(reason: String)
    }

    /// - Parameters:
    ///   - types: raw pasteboard type identifiers (`NSPasteboard.PasteboardType.rawValue`); the app passes all
    ///     types on the pasteboard because some password managers put the marker on a secondary item.
    ///   - sourceBundleID: `org.nspasteboard.source` value, else the frontmost app.
    ///   - ignoredBundleIDs: user setting `clipboardIgnoredApps` (compared case-insensitively).
    public static func decide(types: [String], sourceBundleID: String?, ignoredBundleIDs: [String]) -> Decision {
        if types.isEmpty { return .skip(reason: "empty") }
        if let skip = types.first(where: { skipTypes.contains($0) }) { return .skip(reason: skip) }
        if let source = normalizedBundleID(sourceBundleID) {
            let lowered = source.lowercased()
            if ignoredBundleIDs.contains(where: { $0.trimmingCharacters(in: .whitespaces).lowercased() == lowered }) {
                return .skip(reason: "ignored app")
            }
        }
        return .capture
    }

    /// The source app: a non-empty `org.nspasteboard.source` marker wins over the frontmost app (which is
    /// racy: the user may have switched apps between the copy and our poll).
    public static func sourceBundleID(marker: String?, frontmost: String?) -> String? {
        normalizedBundleID(marker) ?? normalizedBundleID(frontmost)
    }

    static func normalizedBundleID(_ value: String?) -> String? {
        guard let trimmed = value?.trimmingCharacters(in: .whitespacesAndNewlines), !trimmed.isEmpty else {
            return nil
        }
        return trimmed
    }

    /// Inserts `entry` at the front, removing an older entry with the same hash (keeps its pin), and
    /// trims unpinned entries beyond `limit`.
    public static func insert(_ entry: ClipboardEntry, into entries: [ClipboardEntry], limit: Int) -> [ClipboardEntry] {
        var newEntry = entry
        var result = entries
        if let index = result.firstIndex(where: { $0.contentHash == entry.contentHash }) {
            newEntry.pinned = newEntry.pinned || result[index].pinned
            result.remove(at: index)
        }
        result.insert(newEntry, at: 0)
        var unpinnedSeen = 0
        let cap = max(limit, 1)
        return result.filter { item in
            if item.pinned { return true }
            unpinnedSeen += 1
            return unpinnedSeen <= cap
        }
    }
}
